return {
    fov = math.pi / 4,
    clock = 0,
    screenWidth = 0,
    screenHeight = 0,
    wallHeight = 64,
    playerSpeed = 2,
    turnSpeed = 0.002,
    uiActive = false,
    uiElevation = love.graphics.getHeight(),
    uiY = 0,
    poweredUp = 0,
    level = {},
    player = {},
    ghosts = {},
    blinky = {},
    inky = {},
    pinky = {},
    clyde = {},
}
